name: 'Deplot to the S3 using Docker'
description: 'Deploy a static website via AWS S3 using Docker'
inputs:
  bucket:
    description: 'The S3 Bucket name'
    required: true
  bucket-region:
    description: 'The region, where the S3 bucket is stored'
    required: false
    default: 'eu-central-1'
  dist-folder:
    description: 'The folder containing deployable files'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website in S3 Bucket'
runs:
  using: 'docker'
  image: 'Dockerfile'